### PR TITLE
Add Typescript types

### PR DESCRIPTION
**Pull request by BeeeQueue**
Adds types for use in Typescript projects.

### CODE REVIEW

**Comment by BeeeQueue** [comment]
@joaquimserafim Is this project dead? Hello?

**Comment by joaquimserafim** [comment]
Hi, thanks for your attention, and the project is not dead, I am not into typescript and I would love to hear from you why that should be added in the module, a short description if you don't mind, take care mate.

**Comment by BeeeQueue** [comment]
When importing JS projects in TypeScript you have to define its types or you will get a compilation error [(example)](https://github.com/sr-net/auth/blob/b69485b5cb0712dfa0b05943b7500389d2388749/index.d.ts).
Package maintainers are encouraged to add correct types to their packages so users don't have to do it themselves.

**Comment by joaquimserafim** [comment]
Closing since is done in [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/base64-url)

**Pull request closed without merging**
